spring:
  application:
    name: happypay-api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: membership-service
          uri: http://localhost:18081
          predicates:
            - Path=/membership/**
          filters:
            - StripPrefix=0
        - id: banking-service
          uri: http://localhost:18082
          predicates:
            - Path=/banking/**
          filters:
            - StripPrefix=0
        - id: money-service
          uri: http://localhost:18083
          predicates:
            - Path=/money/**
          filters:
            - StripPrefix=0

