spring:
  datasource:
    url: jdbc:mysql://mysql:3306/remittance?serverTimezone=UTC&characterEncoding=UTF-8
    username: local
    password: local
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: [ "kafka:9092" ]
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
service:
  membership:
    url: http://membership-service:8080
  banking:
    url: http://banking-service:8080
  money:
    url: http://money-service:8080
