spring:
  datasource:
    url: jdbc:mysql://mysql:3306/banking?serverTimezone=UTC&characterEncoding=UTF-8
    username: local
    password: local
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
